# Generated by Django 3.2.24 on 2024-03-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer8_app', '0007_auto_20240325_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auvikdevicevendors',
            name='auvik_vendor_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
